buf = [true, false]
arr = [{ "a" = 1 }, { "a" = 2 }]

[[table-array]]
a3 = 1
a2 = 1
a1 = 1

[table-array.b]
c = 1

[[table-array]]
a = 1

[table-array.buf]
a = 1

[table-array.buf.b]
c = 1

[table-array.b]
c = 1
