# 下列字符串的每一个字节都完全相同：
str1 = 'The quick brown fox jumps over the lazy dog.'

str2 = '''
The quick brown \


  fox jumps over \
    the lazy dog.'''

str3 = '''\   
       The quick brown \
       fox jumps over \
       the lazy dog.\
       '''





